version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
  
  frontend:
    build:
      context: ./osdagclient
      dockerfile: Dockerfile
    ports:
      - "5173:5173" 
    volumes:
      - ./osdagclient:/app
    environment:
      - CHOKIDAR_USEPOLLING=true 
    command: npm run dev 


  db:
    image: postgres:14
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
